Batch endpoints
DD-DeCaF/warehouse pull request #22
Opened 2019-12-04 12:57 UTC by annasirunian

Adds endpoints for batch post of fluxomics, metabolomics and proteomics data.

Closes: https://github.com/DD-DeCaF/scrum/issues/1171

2019-12-05 09:28 UTC, kvikshaug requested changes
This is a good start but I think we need to optimize performance before moving forwards.

2019-12-05 09:28 UTC, kvikshaug commented on tests/test_integration/test_endpoints_crud.py
> +        assert proteomics.full_name == proteomics_request["body"][i]["full_name"]
This can be optimized by selecting all the objects in one query using IN operator.

2019-12-05 09:28 UTC, kvikshaug commented on tests/test_integration/test_endpoints_crud.py
> +    n = 100
I would give this var a proper name

2019-12-05 09:28 UTC, kvikshaug commented on src/warehouse/resources.py
> +                    verified_project_ids.add(project_id)
This is very inefficient.

```
0.85s call     tests/test_integration/test_endpoints_crud.py::test_batch_post_metabolomics
0.84s call     tests/test_integration/test_endpoints_crud.py::test_batch_post_fluxomics
0.84s call     tests/test_integration/test_endpoints_crud.py::test_batch_post_proteomics
```

If we assume that many objects will share the same sample, you could first pick all unique sample IDs and bulk select those to verify claims before iterating. Then avoid querying the sample for each object. Something like:

```
 sample_ids = set(flux["sample_id"] for flux in body)
 for sample in models.Sample.query.filter(models.Sample.id.in_(sample_ids)).all():
     jwt_require_claim(sample.condition.experiment.project_id, "write")
```

I'd also move the error handling up by verifying that each of the `sample_ids` actually exists (since bulk select ignores missing ones, not raise exceptions). Then at the point of creating fluxomics objects you know the sample exists and permissions are valid so you don't need to do anything else, and you can just use the id instead of the object.

Note that we do lazy joins on sample -> condition -> experiment. For a single sample I'm able to lower query time from 9ms to 2.7ms with explicit joins, so it's a bit better but if there's only a handful of samples then I'd say it's negligible.

2019-12-05 09:28 UTC, kvikshaug commented on tests/test_integration/test_endpoints_crud.py
> +                "full_name": "Aspartate aminotransferase, mitochondrial",
You could increase test confidence by varying the name for each of the objects to make sure that each insert has the right data. (That's easy to check one by one with the current query below, but if you update it to select multiple objects you might need to make sure the order is correct somehow, maybe order by id or just sort programmatically or something)

2019-12-05 13:52 UTC, annasirunian commented
@kvikshaug thanks for the great suggestions! All comments are addressed now.

2019-12-05 16:11 UTC, kvikshaug approved these changes
Great stuff, just make sure to fix the QA stuff before merging.

2019-12-05 19:06 UTC, merged

2019-12-09 16:24 UTC, BenjaSanchez commented
@annasirunian after the merge of this and https://github.com/DD-DeCaF/caffeine-vue/pull/203 I tested upload of proteomics+growth rate in staging and it works like a charm! 👏